[project]
name = "qrderlybackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-cors-headers>=4.7.0",
    "faker>=37.4.2",
    "faker-food>=0.3.0",
    "pillow>=11.3.0",
]
